import { Subscription } from "../../../domain/entities/Subscription";
import { IFulfillSubscriptionUseCase, IFulfillSubscriptionInput } from "../../IUseCases/subscription/IFulfillSubscriptionUseCase";
import { ISubscriptionRepository } from "../../../domain/repositories/ISubscriptionRepository";
import { ISubscriptionPlanRepository } from "../../../domain/repositories/ISubscriptionPlanRepository";
import { IGymRepository } from "../../../domain/repositories/IGymRepository";
import { AppError } from "../../errors/AppError";
import { HttpStatus } from "../../../constants/statusCodes.constants";

export class FulfillSubscriptionUseCase implements IFulfillSubscriptionUseCase {
    constructor(
        private _subscriptionRepo: ISubscriptionRepository,
        private _planRepo: ISubscriptionPlanRepository,
        private _gymRepo: IGymRepository
    ) {}

    async execute(input: IFulfillSubscriptionInput): Promise<void> {
        const { gymId, planId, paymentIntentId, sessionId } = input;

        const plan = await this._planRepo.findById(planId);
        if (!plan) {
            throw new AppError(`Plan not found: ${planId}`, HttpStatus.NOT_FOUND);
        }

        const gym = await this._gymRepo.findById(gymId);
        if (!gym) {
            throw new AppError(`Gym not found: ${gymId}`, HttpStatus.NOT_FOUND);
        }

        const startDate = new Date();
        const endDate = new Date();
        endDate.setMonth(endDate.getMonth() + plan.durationMonths);

        const subscription = new Subscription(
            "", // ID will be generated by mongo
            gymId,
            gym.gymName || "Gym",
            plan.name,
            plan.price,
            startDate,
            endDate,
            "active",
            "stripe",
            paymentIntentId,
            sessionId
        );

        await this._subscriptionRepo.create(subscription);
    }
}
