import { IGymRepository } from "../../../domain/repositories/IGymRepository";
import { IClientRepository } from "../../../domain/repositories/IClientRepository";
import { ITrainerRepository } from "../../../domain/repositories/ITrainerRepository";
import { ITokenService } from "../../../domain/services/ITokenService";
import { IGoogleAuthUseCase } from "../../IUseCases/auth/IGoogleAuthUseCase";
import { IGoogleAuthService } from "../../../domain/services/IGoogleAuthService";
import { Gym } from "../../../domain/entities/Gym";
import { Client } from "../../../domain/entities/Client";
import { Trainer } from "../../../domain/entities/Trainer";
import { AuthenticationFailedError } from "../../errors/AppError";
import { ISessionRepository } from "../../../domain/repositories/ISessionRepository";
import { Session } from "../../../domain/entities/Session";

export class GoogleAuthUseCase implements IGoogleAuthUseCase {
    constructor(
        private gymRepository: IGymRepository,
        private clientRepository: IClientRepository,
        private trainerRepository: ITrainerRepository,
        private tokenService: ITokenService,
        private googleAuthService: IGoogleAuthService,
        private sessionRepository: ISessionRepository
    ) { }

    async execute(code: string, role: string):
        Promise<{ refreshToken: string }> {

        const email = await this.googleAuthService.getGoogleEmail(code);

        let user: Gym | Client | Trainer | null = null;

        if (role === "gym") {
            user = await this.gymRepository.findByEmail(email);
        } else if (role === "client") {
            user = await this.clientRepository.findByEmail(email);
        } else if (role === "trainer") {
            user = await this.trainerRepository.findByEmail(email);
        }
        if (!user) {
            if (role === "gym") {
                const randomPassword = Math.random().toString(36).slice(-8);
                const newGym = new Gym("", email, randomPassword, role);
                user = await this.gymRepository.create(newGym);
            } else {
                throw new AuthenticationFailedError(`Account not found for ${role}. Please request an invite from a Gym.`);
            }
        }

        if (!user) {
            throw new AuthenticationFailedError("Failed to authenticate user")
        }

        const now = new Date();
        const refreshMaxAge = Number(process.env.REFRESH_MAX_AGE) || 604800; // 7 days in seconds
        const expiredAt = new Date(now.getTime() + refreshMaxAge * 1000);

        const gymId = role === "gym" ? (user as Gym).id : (user as (Client | Trainer)).gymId;

        const session = await this.sessionRepository.create(new Session(
            "", // ID is generated by database
            user.id!,
            role,
            "Unknown (Google Login)",
            "Unknown (Google Login)",
            "Unknown (Google Login)",
            "Unknown",
            now,
            expiredAt,
            now,
            false,
            gymId
        ));

        const refreshToken = this.tokenService.generateRefreshToken({
            id: user.id,
            email: user.email,
            role: role,
            sessionId: session.id,
            gymId: gymId
        })

        return { refreshToken };
    }
}