import { IGymRepository } from "../../../domain/repositories/IGymRepository";
import { IPasswordHasher } from "../../../domain/services/IPasswordHasher";
import { ITokenService } from "../../../domain/services/ITokenService";
import { LoginRequestDTO, LoginResponseDTO } from "../../dtos/auth/LoginDTO";
import { ILoginUseCase } from "../../IUseCases/auth/ILoginUseCase";
import { GymLoginMapper } from "../../mapper/GymLoginMapper";
import { AuthenticationFailedError, NotFoundError } from "../../errors/AppError";
import { Session } from "../../../domain/entities/Session";
import { ISessionRepository } from "../../../domain/repositories/ISessionRepository";

export class GymLoginUseCase implements ILoginUseCase {
    constructor(
        private _userRepository: IGymRepository,
        private _passwordHasher: IPasswordHasher,
        private _tokenService: ITokenService,
        private _sessionRepository: ISessionRepository
    ) { }

    async execute(request: LoginRequestDTO): Promise<LoginResponseDTO> {
        const user = await this._userRepository.findByEmail(request.email);

        if (!user) {
            throw new NotFoundError("Gym not found")
        }

        const isPasswordMatch = await this._passwordHasher.compare(request.password, user.password);
        if (!isPasswordMatch) {
            throw new AuthenticationFailedError("Password Mismatch");
        }

        const now = new Date();
        const refreshMaxAge = Number(process.env.REFRESH_MAX_AGE) || 604800; // 7 days in seconds
        const expiredAt = new Date(now.getTime() + refreshMaxAge * 1000);
        const session = await this._sessionRepository.create(new Session(
            "", // ID is generated by database
            user.id!,
            user.role,
            request.device || "Unknown",
            request.browser || "Unknown",
            request.os || "Unknown",
            request.ip || "Unknown",
            now,
            expiredAt,
            now,
            false,
            user.id
        ));
        const payload = {
            id: user.id,
            email: user.email,
            role: user.role,
            gymId: user.id,
            sessionId: session.id
        };

        const accessToken = this._tokenService.generateAccessToken(payload);
        const refreshToken = this._tokenService.generateRefreshToken(payload);
        console.log(accessToken);
        console.log(refreshToken);
        console.log(GymLoginMapper.toDTO(user, accessToken, refreshToken))
        return GymLoginMapper.toDTO(user, accessToken, refreshToken);
    }
}

