import { IGymRepository } from "../../../domain/repositories/IGymRepository";
import { ISubscriptionRepository } from "../../../domain/repositories/ISubscriptionRepository";
import { ISuperAdminRepository } from "../../../domain/repositories/ISuperAdminRepository";
import { IApproveGymUseCase } from "../../IUseCases/superAd-gym-listing/IApproveGymUseCase";
import { GymResponseDTO } from "../../dtos/superAd-gym-listing/GetAllGymsDTO";
import { NotFoundError, AppError } from "../../errors/AppError";
import { GymMapper } from "../../mapper/SuperAdminGymMapper";
import { Subscription } from "../../../domain/entities/Subscription";

export class ApproveGymUseCase implements IApproveGymUseCase {
    constructor(
        private _gymRepository: IGymRepository,
        private _superAdminRepository: ISuperAdminRepository,
        private _subscriptionRepository: ISubscriptionRepository
    ) { }

    async execute(gymId: string): Promise<GymResponseDTO> {
        // 1. Fetch gym
        const gym = await this._gymRepository.findById(gymId);
        if (!gym) {
            throw new NotFoundError("Gym");
        }

        // 2. Check that the gym is not already approved
        if (gym.approvalStatus === "Approved") {
            throw new AppError("Gym is already approved", 400); // Or 409
        }

        // 3. Fetch superadmin config to get trialDays
        const superAdmin = await this._superAdminRepository.getAdminConfig();
        if (!superAdmin) {
            throw new AppError("SuperAdmin configuration not found", 404);
        }

        const trialDays = superAdmin.trialDays || 28;

        // 4. Update gym approvalStatus -> "approved" and subscriptionStatus -> "Trial"
        // Also update expiryDate on gym for backward compatibility/legacy and easy check
        const startDate = new Date();
        const endDate = new Date();
        endDate.setDate(startDate.getDate() + trialDays);

        const updatedGym = await this._gymRepository.updateStatus(gymId, {
            approvalStatus: 'Approved'
        });

        // 5. Check if gym already has a trial subscription
        const hasTrial = await this._subscriptionRepository.hasTrialSubscription(gymId);

        if (!hasTrial) {
            // 6. Create subscription record
            const trialSubscription = new Subscription(
                "", // id will be generated by db
                gymId,
                "TRIAL",
                0,
                startDate,
                endDate,
                "active",
                null,
                null,
                null,
                startDate
            );

            await this._subscriptionRepository.create(trialSubscription);
        }

        return GymMapper.toResponseDTO(updatedGym);
    }
}
