import { Request, Response, NextFunction } from "express";
import Stripe from 'stripe';
import { ISubscriptionRepository } from "../../../domain/repositories/ISubscriptionRepository";
import { ISubscriptionPlanRepository } from "../../../domain/repositories/ISubscriptionPlanRepository";
import { GymRepository } from "../../../infrastructure/repositories/GymRepository";
import { Subscription } from "../../../domain/entities/Subscription";
import { HttpStatus } from "../../../constants/statusCodes.constants";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || "");

interface StripeCheckoutSession {
    metadata: Record<string, string> | null;
    payment_intent: string | null;
    id: string;
}

export class WebhookController {
    constructor(
        private _subscriptionRepo: ISubscriptionRepository,
        private _planRepo: ISubscriptionPlanRepository,
        private _gymRepo: GymRepository
    ) { }

    async handleStripeWebhook(req: Request, res: Response, _next: NextFunction) {
        const sig = req.headers['stripe-signature'];
        const endpointSecret = process.env.STRIPE_WEBHOOK_SECRET;

        let event;

        try {
            if (!sig || !endpointSecret) {
                console.error("Missing Stripe signature or webhook secret");
                return res.status(HttpStatus.BAD_REQUEST).send('Webhook Error: Missing signature or secret');
            }

            event = stripe.webhooks.constructEvent(req.body, sig, endpointSecret);
        } catch (err) {
            const msg = err instanceof Error ? err.message : "Unknown error";
            console.error(`Webhook Signature verification failed: ${msg}`);
            return res.status(HttpStatus.BAD_REQUEST).send(`Webhook Error: ${msg}`);
        }

        // Handle the event
        switch (event.type) {
            case 'checkout.session.completed': {
                const session = event.data.object as StripeCheckoutSession;
                await this.fullfillSubscription(session);
                break;
            }
            default:
                console.log(`Unhandled event type ${event.type}`);
        }

        res.status(HttpStatus.OK).json({ received: true });
    }

    private async fullfillSubscription(session: StripeCheckoutSession) {
        try {
            const { gymId, planId } = session.metadata || {};

            if (!gymId || !planId) {
                console.error("Missing gymId or planId in session metadata");
                return;
            }

            const plan = await this._planRepo.findById(planId);
            if (!plan) {
                console.error(`Plan not found: ${planId}`);
                return;
            }

            const gym = await this._gymRepo.findById(gymId);
            if (!gym) {
                console.error(`Gym not found: ${gymId}`);
                return;
            }

            const startDate = new Date();
            const endDate = new Date();
            endDate.setMonth(endDate.getMonth() + plan.durationMonths);

            const subscription = new Subscription(
                "", // ID will be generated by mongo
                gymId,
                gym.gymName || "Gym",
                plan.name,
                plan.price,
                startDate,
                endDate,
                "active",
                "stripe",
                session.payment_intent as string,
                session.id
            );

            await this._subscriptionRepo.create(subscription);
            console.log(`Subscription successfully created for gym: ${gym.gymName} (ID: ${gymId})`);

        } catch (error) {
            console.error("Error fulfilling subscription:", error);
        }
    }
}
